server:
  port: 9325


spring:
  r2dbc:
    url: r2dbcs:mysql://127.0.0.1:3306/db_webflux?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

    ## 运行schema失败
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/db_webflux
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema: schema.sql
#    initialization-mode: always